/**
 * Local dataset mapping major Philippine Provinces to their Cities and Municipalities.
 * Since the system is centered around Zamboanga City, the Zamboanga Peninsula provinces are fully listed.
 */
export const PHILIPPINES_LOCATIONS: Record<string, string[]> = {
  "Zamboanga del Sur": [
    "Zamboanga City",
    "Pagadian City",
    "Aurora",
    "Bayog",
    "Dimataling",
    "Dinas",
    "Dumalinao",
    "Dumingag",
    "Guipos",
    "Josefina",
    "Kumalarang",
    "Labangan",
    "Lakewood",
    "Lapuyan",
    "Mahayag",
    "Margosatubig",
    "Midsalip",
    "Molave",
    "Pitogo",
    "Ramon Magsaysay",
    "San Miguel",
    "San Pablo",
    "Sominot",
    "Tambulig",
    "Tigbao",
    "Tukuran",
    "Vincenzo A. Sagun"
  ],
  "Zamboanga del Norte": [
    "Dipolog City",
    "Dapitan City",
    "Bacungan",
    "Baliguian",
    "Godod",
    "Gutalac",
    "Jose Dalman",
    "Kalawit",
    "Katipunan",
    "La Libertad",
    "Labason",
    "Liloy",
    "Manukan",
    "Mutia",
    "Piñan",
    "Polanco",
    "Pres. Manuel A. Roxas",
    "Rizal",
    "Salug",
    "Sergio Osmeña Sr.",
    "Siayan",
    "Sibuco",
    "Sibutad",
    "Sindangan",
    "Siocon",
    "Sirawai",
    "Tampilisan"
  ],
  "Zamboanga Sibugay": [
    "Ipil",
    "Alicia",
    "Buug",
    "Diplahan",
    "Imelda",
    "Kabasalan",
    "Mabuhay",
    "Malangas",
    "Naga",
    "Olutanga",
    "Payao",
    "Roseller Lim",
    "Siay",
    "Talusan",
    "Titay",
    "Tungawan"
  ],
  "Metro Manila": [
    "Manila",
    "Quezon City",
    "Caloocan",
    "Las Piñas",
    "Makati",
    "Malabon",
    "Mandaluyong",
    "Marikina",
    "Muntinlupa",
    "Navotas",
    "Parañaque",
    "Pasay",
    "Pasig",
    "San Juan",
    "Taguig",
    "Valenzuela",
    "Pateros"
  ],
  "Cebu": [
    "Cebu City",
    "Mandaue City",
    "Lapu-Lapu City",
    "Talisay City",
    "Toledo City",
    "Danao City",
    "Bogo City",
    "Carcar City",
    "Naga City",
    "Consolacion",
    "Liloan",
    "Minglanilla",
    "Cordova"
  ],
  "Davao del Sur": [
    "Davao City",
    "Digos City",
    "Bansalan",
    "Hagonoy",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Padada",
    "Santa Cruz",
    "Sulop"
  ],
  "Misamis Oriental": [
    "Cagayan de Oro City",
    "Gingoog City",
    "El Salvador City",
    "Alubijid",
    "Balingasag",
    "Claveria",
    "Gitagum",
    "Initao",
    "Jasaan",
    "Laguindingan",
    "Libertad",
    "Lugait",
    "Magsaysay",
    "Manticao",
    "Naawan",
    "Opol",
    "Salay",
    "Tagoloan"
  ],
  "Bukidnon": [
    "Malaybalay City",
    "Valencia City",
    "Baungon",
    "Cabanglasan",
    "Damulog",
    "Dangcagan",
    "Don Carlos",
    "Impasugong",
    "Kadingilan",
    "Kalilangan",
    "Kibawe",
    "Kitaotao",
    "Lantapan",
    "Libona",
    "Malitbog",
    "Manolo Fortich",
    "Maramag",
    "Pangantucan",
    "Quezon",
    "San Fernando",
    "Sumilao",
    "Talakag"
  ],
  "Benguet": [
    "Baguio City",
    "La Trinidad",
    "Itogon",
    "Sablan",
    "Tuba",
    "Tublay",
    "Atok",
    "Bakun",
    "Bokod",
    "Buguias",
    "Kabayan",
    "Kapangan",
    "Mankayan"
  ],
  "Cavite": [
    "Bacoor City",
    "Dasmariñas City",
    "Imus City",
    "Cavite City",
    "Tagaytay City",
    "Trece Martires City",
    "General Trias City",
    "Silang",
    "Kawit",
    "Noveleta",
    "Rosario",
    "Tanza",
    "Naic",
    "Maragondon",
    "Alfonso",
    "Indang",
    "Mendez",
    "Amadeo",
    "General Emilio Aguinaldo",
    "Magallanes",
    "Ternate",
    "Carmona"
  ],
  "Laguna": [
    "Biñan City",
    "Cabuyao City",
    "Calamba City",
    "San Pedro City",
    "Santa Rosa City",
    "San Pablo City",
    "Santa Cruz",
    "Los Baños",
    "Bay",
    "Pila",
    "Victoria",
    "Nagcarlan",
    "Liliw",
    "Majayjay",
    "Magdalena",
    "Pagsanjan",
    "Lumban",
    "Kalayaan",
    "Paete",
    "Pakil",
    "Pangil",
    "Siniloan",
    "Famy",
    "Mabitac",
    "Santa Maria",
    "Alaminos",
    "Rizal",
    "Cavinti",
    "Luisiana"
  ],
  "Pampanga": [
    "Angeles City",
    "Mabalacat City",
    "San Fernando City",
    "Arayat",
    "Bacolor",
    "Candaba",
    "Floridablanca",
    "Guagua",
    "Lubao",
    "Macabebe",
    "Masantol",
    "Mexico",
    "Minalin",
    "Porac",
    "San Luis",
    "San Simon",
    "Santa Ana",
    "Santa Rita",
    "Santo Tomas",
    "Sasmuan"
  ],
  "Iloilo": [
    "Iloilo City",
    "Passi City",
    "Oton",
    "Pavia",
    "Santa Barbara",
    "Cabatuan",
    "Janiuay",
    "Dumangas",
    "Barotac Nuevo",
    "Pototan",
    "Dingle",
    "Dueñas",
    "Passi",
    "Estancia",
    "Carles",
    "Miagao",
    "Guimbal",
    "Tigbauan",
    "Leganes"
  ]
};

export const PROVINCES = Object.keys(PHILIPPINES_LOCATIONS).sort();
